apiVersion: v1
kind: Pod
metadata:
  name: env-pod
  namespace: sandbox
spec:
  containers:
  - name: env-container
    image: nginx:latest
    ports:
    - containerPort: 80
  env:
  - name: DEMO_GREETING
    value: "hello from the environment"
  - name: DEMO_FAREWELL
    value: "such a sweet sorrow"