apiVersion: v1
kind: Pod
metadata:
  name: nodeport-pod
  labels:
    name: nodeport
    env: dev
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodepor-service
spec:
  type: NodePort
  selector:
    name: nodeport
    env: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80