apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ds
  labels:
    app: webapplication
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment-set
  template:
    metadata:
      labels:
        app: nginx-deployment-set
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-deployment-set
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80