apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeport-pod
  labels:
    name: nodeport-service
    demo: service
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80   #here with this line port will not be opened, just for information
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    name: nodeport-service
    demo: service
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #container-port