apiVersion: v1
kind: Pod
metadata:
  name: nginx-load-balancer-pod
  labels:
    name: load-balancer-service
    demo: service
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80   #here with this line port will not be opened, just for information
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer
spec:
  type: LoadBalancer
  selector:
    name: load-balancer-service
    demo: service
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #container-port