apiVersion: v1
kind: Pod
metadata:
  name: taint-tolerations
spec:
  # list of containers
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerPort: 80
  tolerations:
  - key: "env"
    operator: "Equal"
    value: "dev"
    effect: "NoSchedule"
