apiVersion: v1
kind: Pod
metadata:
  name: label-demo-jella-praveen
  namespace: roboshop
  labels:
    course: DevOps
    trainer: praveen

spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
      - containerPort: 80