apiVersion: v1
kind: Pod
metadata:
  name: config-pod

spec:
  containers:
  - name: config-pod-container
    image: nginx
    env:    # fetching required variables using method-1 (Lengthy method)
    - name: boomingCloudIs
      valueFrom:
        configMapKeyRef:
          name: demonstration-of-configmap
          key: cloud

    - name: AutomationUsing123
      valueFrom:
        configMapKeyRef:
          name: demonstration-of-configmap
          key: automation


---

apiVersion: v1
kind: Pod
metadata:
  name: config-pod-2

spec:
  containers:
  - name: config-pod-container2
    image: nginx
    envFrom:    # fetching all the variables using method-2 (Simple method)
      - configMapRef:
          name: demonstration-of-configmap