apiVersion: v1
kind: Pod
metadata:
  name: config-pod

spec:
  containers:
  - name: config-pod-container
    image: nginx
    env:
    - name: boomingCloudIs-
      valueFrom:
        configMapKeyRef:
        name: demonstration-of-configmap
        key: cloud